### ISSUE TITLE
-url not working???

### ISSUE THREAD

**Issue by fidofido300** [jvlflame/Javinizer#11]
Tried The Following command 
Javinizer -Path "W:\JAV\Censored-new\A-G\ekw-019\" -DestinationPath "W:\JAV\Censored-new\A-G\" -Url "https://www.r18.com/videos/vod/movies/detail/-/id=2ekw00019/?i3_ref=search&i3_ord=1"
But I get 
[Javinizer] Function started
[Javinizer] Sort path set to: [W:\JAV\Censored-new\A-G\ekw-019\]
[Javinizer] Destination path set to: [W:\JAV\Censored-new\A-G\]
[Javinizer] (1 of 1) Sorting [EKW019.mp4]
WARNING: [Get-R18Url] Search [EKW-019] not matched on R18/Dmm
WARNING: [Get-R18Url] Search [EKW-019] not matched on R18/Dmm
VERBOSE: [Javinizer] Ended sort on [EKW019.mp4]

Shouldn't this scrape EKW019 ??
Which by the way exist at r18 but not EKW-019
Thanks
2.
3.
4.

## Your Environment

* Module version used:
* Operating System and PowerShell version:

**Comment by jvlflame** [comment]
I'm unable to reproduce the error you're receiving in my environment. What version of the module are you using?

```powershell
Javinizer -Path '.\EKW-019.mp4' -Url "https://www.r18.com/videos/vod/movies/detail/-/id=2ekw00019/?i3_ref=search&i3_ord=1"
```

Javinizer's regular sort will clean the filename from `EKW019.mp4` to `EKW-019` before attempting to search for it. Due to that, videos with non-standard naming such as `EKW019` on R18 will error out. 

**To bypass this, you can use the `-Strict` parameter to read filenames as is.**

Try running
```powershell
Javinizer -Path "W:\JAV\Censored-new\A-G\ekw-019" -DestinationPath "W:\JAV\Censored-new\A-G" -Strict
```

**Comment by fidofido300** [comment]
Ok! the Command you provided do scrape the movie Thank you!
But
Shouldn't it scrape with the provided url aswell because 
 Javinizer -Path "W:\JAV\Censored\A-G\ekw-019\" -DestinationPath "W:\JAV\Censored-new\A-G\" -Url "http://www.javlibrary.com/en/?v=javlilzvsm,https://www.r18.com/videos/vod/movies/detail/-/id=2ekw00019/?i3_ref=search&i3_ord=1,https://www.dmm.co.jp/digital/videoa/-/detail/=/cid=2ekw00019/?i3_ref=search&i3_ord=1" -Multi -Apply
[Javinizer] Function started
[Javinizer] Sort path set to: [W:\JAV\Censored\A-G\ekw-019\]
[Javinizer] Destination path set to: [W:\JAV\Censored-new\A-G\]
VERBOSE: [Javinizer] Ended sort on [EKW019.mp4]
WARNING: [Get-R18Url] Search [EKW-019] not matched on R18/Dmm
WARNING: [Get-R18Url] Search [EKW-019] not matched on R18/Dmm
VERBOSE: [Javinizer] Sort has completed or has been stopped prematurely; Stopping all running jobs...
VERBOSE: [Javinizer] Ended sort on [EKW019.mp4]
Javinizer -Path "W:\JAV\Censored\A-G\ekw-019\" -DestinationPath "W:\JAV\Censored-new\A-G\" -Url "http://www.javlibrary.com/en/?v=javlilzvsm,https://www.r18.com/videos/vod/movies/detail/-/id=2ekw00019/?i3_ref=search&i3_ord=1,https://www.dmm.co.jp/digital/videoa/-/detail/=/cid=2ekw00019/?i3_ref=search&i3_ord=1" -Multi -Apply -Strict
[Javinizer] Function started
[Javinizer] Sort path set to: [W:\JAV\Censored\A-G\ekw-019\]
[Javinizer] Destination path set to: [W:\JAV\Censored-new\A-G\]
VERBOSE: [Javinizer] Ended sort on [EKW019.mp4]
WARNING: [Get-JavlibraryUrl] Search [EKW019] not matched on JAVLibrary
VERBOSE: [Javinizer] Sort has completed or has been stopped prematurely; Stopping all running jobs...
VERBOSE: [Javinizer] Ended sort on [EKW019.mp4]

As you can see the url provided is not used program tries to find the url itself which I think shouldn't do because we already provided it.

Thank You

**Comment by jvlflame** [comment]
When you use the `-Url` parameter, you need to reference the file directly in the `-Path` parameter, rather than the directory path. For example: 
```
# This will work
Javinizer -Path "W:\JAV\Censored\A-G\ekw-019\ekw019.mp4" -Url "https://(...)"

# This will NOT work
Javinizer -Path "W:\JAV\Censored\A-G\ekw-019" -Url "https://(...)"
```

When you reference a directory path in `-Path`, it will automatically try to run a directory sort which is why it's still trying to search for the url.

In cases like this for single files, you probably wouldn't need to use `-Multi`. Additionally, `-Apply` should only be used in cases where you don't want to specify `-Path` or `-DestinationPath` in your command.

**Comment by fidofido300** [comment]
Ohhh
OK 
Thank You!
