### ISSUE TITLE
Feature Request: Using DeepL Translate API to translate titles and descriptions

### ISSUE THREAD

**Issue by ahcnguyen** [jvlflame/Javinizer#140]
First of all, fantastic app, my collection has never looked better in Jellyfin!

I know that Javinizer uses Google Translate to machine-translate Japanese titles & descriptions, and the results can be quite...poetic. I've used DeepL Translator for quick translations of small bits of text and the results often make much more sense.

Wonder if there's a DeepL API that Javinizer can use...

**Comment by jvlflame** [comment]
I did a bit of research into DeepL, and it seems like they do provide an API. But like most services, they require a paid subscription to use, which I'm assuming most people aren't willing to pay for.

I can do some poking around for other free tools, but in the free sphere there's probably a limited amount of options.

**Comment by Avatarthe** [comment]
I must agree, Deepl translations are far superior to Google. I have been using this program to translate Chinese subtitles into English
https://github.com/firebfm/deepl-srt
and the results are petty impressive compared to google, perhaps you could look at the technique the programmer used to access Deepl with Selenium and use a similar technique so we can get real descriptions.

Thanks again fro this program , it rocks!

**Comment by jvlflame** [comment]
DeepL support via the developer API (which now has a free tier) is tentatively available by replacing one of the existing translation scripts [translate.py](https://github.com/jvlflame/Javinizer/blob/master/src/Javinizer/translate.py) or [translate_new.py](https://github.com/jvlflame/Javinizer/blob/master/src/Javinizer/translate_new.py) and filling in the `apikey = "YOUR-API-KEY"` line. I don't think it's feasible to add DeepL scraping functionality via headless browser due to how the threading works in Javinizer. I will try to add the developer API natively next release.

```
# Written by toastyice
import sys
import requests
import tempfile
import os
import json
apikey = "YOUR-API-KEY"
lang = "EN-GB"

url = "https://api-free.deepl.com/v2/translate?auth_key={}&text={}&target_lang={}".format(apikey, sys.argv[1], lang)
r = requests.get(url)
j = json.loads(r.text)
n = j['translations'][0]['text']

text = n.encode('utf8')

# Write the translated text to a temporary file to bypass encoding issues when redirecting the text to PowerShell
new_file, filename = tempfile.mkstemp()
os.write(new_file, text)
os.close(new_file)

# Return the path to the temporary file to read it from PowerShell
print(filename)
```
