### ISSUE TITLE
[Feature Request] Male actor names

### ISSUE THREAD

**Issue by ozawaslave** [jvlflame/Javinizer#147]
Male actor names can be imported from http://avdanyuwiki.com/ using the dmm ID

For example, [http://avdanyuwiki.com/?s=miae00311](http://avdanyuwiki.com/?s=miae00311)

出演AV男優 ： 平田司, 松山伸也, 結城結弦	 
Cast AV actors: Tsukasa Hirata, Shinya Matsuyama, Yuzuru Yuki

The site also contains other metadata that is on dmm, javlibrary, etc. Including covers, actress names, director names, plot, etc.

**Comment by jvlflame** [comment]
Never heard of that site, but it's definitely something that I think is worth exploring.
I'll take a look and see how feasible it would be to add it.

**Comment by jvlflame** [comment]
Another site that may be of use is http://www.minnano-av.com/ for actors.
Also asianscreens from #118.

**Comment by ozawaslave** [comment]
I've never done any powershell scripting, but I'm looking at the other scrapers in private. 

I wrote up a mockup in Python.

```python
# Get page from web.
with urllib.request.urlopen("https://avdanyuwiki.com/?s=" + dmm_id) as url:
    s = url.read()

# HTML parser in Python
soup = BeautifulSoup(s, "html.parser")
    
# create an object of all instances of class="post-tags" 
spans = soup.find_all('span', {'class' : 'post-tags'})

# We only need the first one. A high number of span elements might mean more than one title was found
actors = spans[0].get_text()[1:].split(', ')
```

I could probably figure Powershell out and incorporate into the existing ecosystem.

**Comment by jvlflame** [comment]
I don't think my issue with scraping the site is the issue per se, but rather how to integrate it with the current Javinizer workflow.
I did some research a while ago into how I could get this to work, be it as an independent scraper or just scraping the actors.

The site also seems to work pretty weird with how it outputs the search results, but it's still doable to parse. Another issue is how to parse the thumburls for the male actors. I'm thinking since there's only a limited amount of them, to actually just parse and hardcode their names in the code to assign them.

If this scraper were implemented, would you use this as your primary actor metadata scraper? Because my assumption is that most people are using english for actor names, and unless it was possible to somehow combine the male actor names with those of another scraper it wouldn't be of much use.

**Comment by ozawaslave** [comment]
So I have a tool I built I could upload as a stand-alone. It will go through the folder your library is located in, open every .nfo file and just add the male actors after scraping. I'm not worried about thumbnails for the time being. I agree, the current workflow for the scraperes is setup so they can each be used independently, where this would just be more of an add-on and not a primary source of other metadata.

**Comment by jvlflame** [comment]
Let's leave this open for now. I still want to implement this, but I'm going to be doing some testing of how the actress metadata is joined together and that will take a bit longer.
