### ISSUE TITLE
Can we have <ACTRESS> added as a tag?

### ISSUE THREAD

**Issue by Logi-Ca1** [jvlflame/Javinizer#15]
Hi,

Thanks for the great work on this module! It does what I have been looking for, for quite a while. Only thing is that I wish that we can have the actress name as a tag, since I'm used to the following format: ACTRESS - TITLE - ID. 

If you do not feel like this is worth the trouble, feel free to close this issue. Again, thanks for writing this tool :)

**Comment by jvlflame** [comment]
I can add it for the next release since it's requested.

My reasoning for not including it originally is due to OS path length restrictions. Occasionally you'll have a video with 10+ different actresses and it tended to error out or require manual intervention to fix.

I will add the tag as `<ACTORS>` to conform to JAVMovieScraper's standards.

**Comment by jvlflame** [comment]
Added in [release 1.1.13](https://github.com/jvlflame/Javinizer/releases/tag/1.1.13).
