### ISSUE TITLE
Feature Request: add non dvd censored jav

### ISSUE THREAD

**Issue by Freakboo** [jvlflame/Javinizer#151]

**Comment by NewMember12345** [comment]
I was just thinking about this as a feature request. 

MGStage has a yes/no age check on first time connection. Then the url's are very predicable. like https://www.mgstage.com/product/product_detail/300MAAN-123/

The Posters shown is clickable and has predictable URL addresses. The poster though is inconsistent between different series. for example, 259luxu the images are always on the right half of the poster pic. But most of the other series is a horizontal screen shot so to generate a poster, it is not just simply cutting it to center middle. 

But i'd love it if javinizer can scrape MGStage for nfo titles, dates, ID. The actresses on there are not their real JAV names. I usually cross reference it manually on http://sougouwiki.com to figure out who it actually is. 

I am not a coder, I barely got the CLI working. GUI never worked for me. but I'd really appreciate it if this feature can be added.

**Comment by jvlflame** [comment]
I'll work on this.

Good callout on the posters. I'm not sure I'll be able to put in a clean solution to handling the poster issue that you mentioned @NewMember12345 . Since the current method involves doing a aspect ratio based crop on the cover image, this would end up very weird for some of them.

I'll see how far I can get with this.
