### ISSUE TITLE
Translation in Spanish Issue

### ISSUE THREAD

**Issue by kronometroz** [jvlflame/Javinizer#152]
## Expected Behavior
translation without errors

## Current Behavior
resulting translation of plot with strange characters in accents, ñ, etc , i.e: for VRTM-107:

<plot>Un chequeo m├®dico realizado una vez al a├▒o en la escuela. Ni├▒as que son diagnosticadas por un m├®dico enviado desde un determinado hospital "Recogen las secreciones en la vagina y env├¡anlas a la agencia de inspecci├│n". Ni├▒as que escuchan las instrucciones del m├®dico sin ninguna duda. Varias cosas llamadas instrumentos m├®dicos se insertan a trav├®s de la cortina en una peque├▒a grieta sin desarrollar. ÔÇ£Esta es tu membrana virgen, ┬┐puedes verla?ÔÇØ Incluso se insert├│ una co-c├ímara en la vagina de una estudiante ...</plot>

## Steps to Reproduce (for bugs)
"sort.metadata.nfo.translatedescription.language": "es",

## Your Environment
* Module version used: 2.1.6
* Operating System and PowerShell version: 7

**Comment by jvlflame** [comment]
Thanks for reporting the issue. It'll be fixed in the next version.

The translation module is also being switched from [googletrans](https://github.com/ssut/py-googletrans) to [google_trans_new](https://github.com/lushan88a/google_trans_new) due to frequently occurring errors on the original module.
