### ISSUE TITLE
Feature Request: Subtitles follow-up

### ISSUE THREAD

**Issue by raenoll** [jvlflame/Javinizer#197]
## Expected Behavior
Move subtitles (ABP-001.chi.srt) with movie (ABP-001.mp4) to the same destination path. 

srt / ssa / ass / smi

## Current Behavior
Do nothing

## Your Environment
* Module version used: 2.2.11
* Operating System and PowerShell version: debian 10 / PowerShell 7.1.1

**Comment by jvlflame** [comment]
Do subtitle files need to be renamed to the same as the movie name?

**Comment by raenoll** [comment]
> Do subtitle files need to be renamed to the same as the movie name?

Subtitles of filenames should be the same as the movie name plus ISO language code (2-letter or 3-letter) if available. This fits [Plex](https://support.plex.tv/articles/200471133-adding-local-subtitles-to-your-media/) platform. Emby/Jellyfin may vary.

**Comment by jvlflame** [comment]
Could you provide some examples of the subtitle filenames that are included with the movies? If it requires a language code then I assume that will need to be pulled from the filemame.

**Comment by raenoll** [comment]
> Could you provide some examples of the subtitle filenames that are included with the movies? If it requires a language code then I assume that will need to be pulled from the filemame.


```
ABP-001.mp4
ABP-001.chi.ass
ABP-001.jpn.srt
ABP-001.eng.srt

ABP-002.mp4
ABP-002.en.srt
ABP-002.ja.srt
ABP-002.zh.srt
```

**Comment by jvlflame** [comment]
Thanks. So the subtitle files are usually also pulled from the root level of the movie directory as well?
Do you know if there are any cases where the subtitle files are included in a nested folder?

**Comment by raenoll** [comment]
> Thanks. So the subtitle files are usually also pulled from the root level of the movie directory as well?

They should be at the same level of directory mostly as far as I know.

> Do you know if there are any cases where the subtitle files are included in a nested folder?

I haven't seen this before. Probably for backup in the future if they are in a nested folder because they are unreadable.

Plex / Emby users may use non-standard language codes. In Plex, non-standard language code of subtitle can't be recognized to correct language and converted to unknown language.

**Comment by raenoll** [comment]
In some desktop media players, there may have default settings to read subtitles in subdirectories such as subs, subtitles or custom ones.

**Comment by idontknownl** [comment]
Hi jviflame,

I would love to assist in getting this enhancement developed, as It is really bugging me as it takes a lot of time to move the subtitles one by one. Any way I can assist? 

I think the easiest implementation could be to expect the user to correctly name the file and have javinizer simply move it in the correct folder during the scan.

**Comment by jvlflame** [comment]
@idontknownl Hi there, honestly this probably isn't too hard of a feature to add, but my focus on this project has notably declined since starting to work on other projects. I'll take a look at implementing it in this upcoming week.

**Comment by jvlflame** [comment]
@idontknownl In your experience, do the subtitle files come with the standard naming scheme of `<MOVIE>.<LANG>.<EXT>` that @raenoll provided above? If so, I can add a blanket check for the language in the filename, otherwise it may get more complicated. I'd rather the user not have to rename the subtitle files themselves so I'm hoping that the downloaded subtitles are consistently named.

> ABP-001.mp4
ABP-001.chi.ass
ABP-001.jpn.srt
ABP-001.eng.srt

> ABP-002.mp4
ABP-002.en.srt
ABP-002.ja.srt
ABP-002.zh.srt

**Comment by idontknownl** [comment]
I jvflame, indeed I easily added the subtitle format I was interested (i am using ASS) to your script, so it recognizes, renames, and allocates it in the correct folder, It is not elegant but it works.  the only issue as you pointed out above I lose the language code (but I am not interested in multiple languages at this time so is fine). 
The format depends on who makes the subtitle but that is the standard format that is recognized by plex/kodi etc otherwise the subtitle will not be automatically associated.
