### ISSUE TITLE
Plans To Support arm/v7?

### ISSUE THREAD

**Issue by Emilaia** [jvlflame/Javinizer#297]
## Current Behavior
Whenever you attempt to build with the docker image on a raspberry pi, you'll be greeted with the following whenever the container starts its execution:
`standard_init_linux.go:228: exec user process caused: exec format error`
Which of course, stems from an incompatible image. 

So I just wanted to ask, are there were any plans to add images for arm/v7?

## Your Environment
* Module version used: latest (tried both regular and experimental arm64v8 version)
* Operating System and PowerShell version: Latest Raspbian OS on Raspberry 4
![image](https://user-images.githubusercontent.com/90160228/132143988-c6c5d02e-7ffb-4c37-9e50-f340f07b6d2b.png)
![image](https://user-images.githubusercontent.com/90160228/132144038-f985736a-4428-4640-a5ba-2fcadf254176.png)

**Comment by jvlflame** [comment]
Hey there, I tried setting up an arm-compatible image a while back in #276 , but unfortunately I couldn't get it to run properly for a couple reasons:
1. I don't have a arm64 environment to properly test on
2. The PowerShell Universal runtime that Javinizer runs on (v1.5.13) requires a more recent version (v2+) to use the arm64-compatible version which I probably don't have the motivation to migrate to
3. It's possible there are bugs/breaking changes on the current version of the arm64 PowerShell Universal runtime

Unfortunately I didn't save the most recent arm64 dockerfile I was testing with but if you want to try building it yourself locally you can take a look at the current [Dockerfile](https://github.com/jvlflame/Javinizer/blob/master/Dockerfile) and adapting it with  an arm64-compatible image and pointing the PowerShell Universal download to the latest version https://imsreleases.blob.core.windows.net/universal/production/2.2.1/Universal.linux-arm64.2.2.1.zip. 

Otherwise I would recommend just sticking with running on either Windows or Docker on a linux system.

**Comment by Emilaia** [comment]
Understandable, thank you.
