### ISSUE TITLE
Is it possible to add support for uncensored movie?

### ISSUE THREAD

**Issue by DARKENEGET** [jvlflame/Javinizer#34]
Hi,

I've just notice that planned road-map regarding uncensored type have been remove in the recently release.

That sadly since this is also one of my waiting list.

So, may I ask about in the future? Is it possible to do meta-data scrape for this kind of movie?
These are many website that provide the data such as official site or AVSOX in example.

Regards.

**Comment by jvlflame** [comment]
My main issue with scraping uncensored content is that there's no standardization of the metadata.
Movie IDs, genres, studio names, etc. are all different (eg. fc2, 1pondo, etc.) and in my opinion a nightmare to handle all of them.

I might revisit the idea again, but I'll be honest it's not one of my top priorities since I don't really download or watch any uncensored JAV.

**Comment by DARKENEGET** [comment]
Thank you for your attention.

I understand that uncensored contents doesn't have the standardization of the metadata.
How about add an option to specific which studio to scrape?

Such as if I prefer 1Pondo, then it's scrape from 1Pondo official or JavBus with 1Pondo specification.

**Comment by fidofido300** [comment]
Or 
https://www.aventertainments.com/ppv

**Comment by jvlflame** [comment]
Added javbus in release 1.5.0

**Comment by jvlflame** [comment]
Added jav321 in release 1.6.0.
