### ISSUE TITLE
dl.getchu.com Metadata Collection

### ISSUE THREAD

**Issue by stratusDunoa** [jvlflame/Javinizer#51]
Hello! I wanted to start off by thanking you for this project. This tool has accomplished what I previously thought was going to be an insurmountable task of organization, and so far it's fixed up ~400 javs I've had sitting around, with many more to go. 

I was wondering if adding dl.getchu.com to the list of supported sites would be feasible. I happen to have a lot of doujin javs that unfortunately are not recorded in JAVLibrary or any of the other sites. Based on some observations, it doesn't look like many of these doujin javs conform to a standard coding system (like XYZ-001), so the URL parameter may need to employed to properly gather metadata. Getchu seems to have product codes for each item, so that could be a possible identifier.

**Comment by jvlflame** [comment]
Took a look into it.. it does seem feasible at least for the metadata collection part.

Though like you mentioned, there's not really a realistic way of doing a quick match/sort of these by product ID since the original downloaded filenames probably wouldn't include it. I guess one possibility is by searching using the filename if it includes the movie title to match, but from my experience they don't usually match up, and would probably get wildly inaccurate results.

I'll look into seeing if I could implement it with the `-Url` parameter as a requirement.
