### ISSUE TITLE
How to recursive but output in sub folder?

### ISSUE THREAD

**Issue by orophix** [jvlflame/Javinizer#62]
I have this kind of folder structure:

Main Folder
  - Genre 1
  - Genre 2

I want to run the script recursively from the main folder and when in goes into Genre 1 I want it to make the folders inside of Genre 1 and once it finishes all the Genre files and moves onto Genre 2 I want all the files that were in Genre 2 to be turned into folders in Genre 2.

Currently it throws everything into main folder.

Is there a way to do this?

**Comment by jvlflame** [comment]
If -DestinationPath isn't specified, it will default to the -Path folder as the output which is why you're running into that issue.

You could just go one-by-one into the Genre folders:
```powershell
Javinizer -Path 'C:\MainFolder\Genre1'
Javinizer -Path 'C:\MainFolder\Genre2'
Javinizer -Path 'C:\MainFolder\Genre3'
```
Or you could write a loop to run Javinizer if you have a lot of folders
```powershell
# Specify your Main Folder path
$folderPath = 'C:\MainFolder'

# Gets all the folders inside your Main Folder
$genreFolders = Get-ChildItem -Path $folderPath -Directory

# Runs Javinizer individually on each folder inside your main folder
$genreFolders | ForEach-Object { Javinizer -Path $_ }

# One-liner
gci 'C:\MainFolder\' -Directory | % { Javinizer $_ }
```

For each of the Javinizer commands, add -Recurse if your genre folders aren't flat.

**Comment by jvlflame** [comment]
Closed
