### ISSUE TITLE
Bug: unable to find these videos, but they do exist on sites

### ISSUE THREAD

**Issue by zuko7177** [jvlflame/Javinizer#85]
Tested alpha10 on 50+ videos. Great work on this release! 

Here's 3 video example that it did not find, but they do exists on the sites.
![image](https://user-images.githubusercontent.com/39366879/93033472-47444e80-f5eb-11ea-955d-0bdc260a6e83.png)

HMPD-10042
DMM: https://www.dmm.co.jp/mono/dvd/-/detail/=/cid=41hmpd10042/?i3_ref=search&i3_ord=1

HMPD-10047
DMM: https://www.dmm.co.jp/mono/dvd/-/detail/=/cid=41hmpd10047/?i3_ref=search&i3_ord=1

HHED-055
R18: https://www.r18.com/videos/vod/movies/detail/-/id=h_086hhed00055/?i3_ref=search&i3_ord=1
JavLibrary: http://www.javlibrary.com/en/?v=javli73nty

**Comment by jvlflame** [comment]
For whatever reason, HMPD10042 and HMPD10047 don't show up when you search for them in DMM. That's why they're not being found. Unfortunately there's no way around that unless I make it fall back to the ID that was found from R18 (which was the method used in v1.x.x).

As for HHED-055, it doesn't follow the standard 3 number ID schema on Javlibrary, so that's why it's not matching properly.
![image](https://user-images.githubusercontent.com/17932235/93034214-334e1c00-f5ee-11ea-8682-3aca87e2187a.png)

Javinizer's automatic ID matching/renaming requires that the ID match exactly what is listed at the source as to avoid mismatches. 
For example, if you did `Javinizer -Find HHED-055 -Javlibrary` it would fail, but if you did `Javinizer -Find HHED-55 -Javlibrary` it would find it successfully.

You can see this in action when you run with `-Debug`.
![image](https://user-images.githubusercontent.com/17932235/93034315-8627d380-f5ee-11ea-848d-e8ceee5c24cb.png)

Unfortunately I don't think I could write in logic to match these fringe cases due to it most likely causing issues elsewhere. But the way around it is using the `-Strict` parameter when sorting or using the regex match to match filenames exactly by their ID rather than automatically converting them to their standard format. You would name the file `HHED-55.mp4` and then run `Javinizer -Path 'path/to/HHED-55.mp4' -Strict` and it would set the ID to `HHED-55` rather than `HHED-055`.

**Comment by zuko7177** [comment]
No worries about HHED-055. As you said these are fringe cases and should not come up often. When they do, it's easy enough to do the work-around.
Feel free to close this ticket.
Great job on this release. I've been testing it further without issues.

**Comment by jvlflame** [comment]
Thanks for raising this issue though.
I'll update the documentation to include these cases.
